# Generated by Django 5.0.7 on 2024-09-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Car image')),
            ],
        ),
        migrations.CreateModel(
            name='Car2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_images', verbose_name='Car image')),
                ('name', models.CharField(max_length=100, verbose_name='Car name')),
                ('price', models.PositiveIntegerField(verbose_name='Car Price')),
                ('running', models.FloatField(verbose_name='Car running')),
                ('horsepower', models.PositiveIntegerField(verbose_name='Car horsepower')),
                ('transmission', models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual')], max_length=30, verbose_name='Transmission name')),
                ('about', models.TextField(verbose_name='Car about')),
                ('date', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(verbose_name='Car year')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Car Price')),
            ],
        ),
        migrations.AlterModelOptions(
            name='car',
            options={},
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
