# Generated by Django 5.0.7 on 2024-09-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_brand_car2_contacts_price_alter_car_options_car_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car2',
            name='about',
        ),
        migrations.RemoveField(
            model_name='car2',
            name='date',
        ),
        migrations.RemoveField(
            model_name='car2',
            name='horsepower',
        ),
        migrations.RemoveField(
            model_name='car2',
            name='name',
        ),
        migrations.RemoveField(
            model_name='car2',
            name='running',
        ),
        migrations.RemoveField(
            model_name='car2',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='car2',
            name='year',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='logo',
        ),
        migrations.AddField(
            model_name='logo',
            name='image',
            field=models.ImageField(default=1, upload_to='images', verbose_name='Logo image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(verbose_name='Car year'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Logo Name'),
        ),
    ]
