# Generated by Django 5.0.7 on 2024-09-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_car2_about_remove_car2_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='image',
            new_name='img',
        ),
    ]
