# Generated by Django 5.0.7 on 2024-09-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_image_logo_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='icon',
            new_name='img',
        ),
    ]
