# Generated by Django 5.0.7 on 2024-09-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_service_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_images', verbose_name='Car image')),
                ('price', models.PositiveIntegerField(verbose_name='Car Price')),
            ],
        ),
        migrations.AddField(
            model_name='car2',
            name='about',
            field=models.TextField(default=1, verbose_name='Car about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car2',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='car2',
            name='horsepower',
            field=models.PositiveIntegerField(default=1, verbose_name='Car horsepower'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car2',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Car name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car2',
            name='running',
            field=models.FloatField(default=1, verbose_name='Car running'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car2',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual')], default=1, max_length=30, verbose_name='Transmission name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car2',
            name='year',
            field=models.IntegerField(default=1, verbose_name='Car year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Car image'),
        ),
        migrations.AlterField(
            model_name='car2',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Car image'),
        ),
    ]
