# Generated by Django 5.0.7 on 2024-09-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_car3_car2_about_car2_date_car2_horsepower_car2_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car3',
        ),
    ]
