# Generated by Django 5.0.7 on 2024-09-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_car3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car2',
            name='about',
        ),
        migrations.RemoveField(
            model_name='car2',
            name='name',
        ),
        migrations.AddField(
            model_name='car2',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car2',
            name='make',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car2',
            name='model',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
