# Generated by Django 5.0.7 on 2024-09-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_car2_about_remove_car2_name_car2_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car2',
            name='image',
        ),
        migrations.AddField(
            model_name='car2',
            name='img',
            field=models.ImageField(default=1, upload_to='img', verbose_name='Car image'),
            preserve_default=False,
        ),
    ]
