# Generated by Django 5.0.7 on 2024-09-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_car2_image_car2_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car2',
            new_name='Cars',
        ),
    ]
