# Generated by Django 5.0.7 on 2024-09-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_car2_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='img',
        ),
        migrations.AddField(
            model_name='cars',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Car image'),
            preserve_default=False,
        ),
    ]
