# Generated by Django 5.0.7 on 2024-09-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_cars_img_cars_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='make',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='model',
        ),
        migrations.AddField(
            model_name='cars',
            name='about',
            field=models.TextField(default=1, verbose_name='Car about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Car name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Car image'),
        ),
    ]
