# Generated by Django 5.0.7 on 2024-09-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_cars_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Car image')),
                ('name', models.CharField(max_length=100, verbose_name='Car name')),
                ('price', models.PositiveIntegerField(verbose_name='Car Price')),
                ('running', models.FloatField(verbose_name='Car running')),
                ('horsepower', models.PositiveIntegerField(verbose_name='Car horsepower')),
                ('transmission', models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual')], max_length=30, verbose_name='Transmission name')),
                ('about', models.TextField(verbose_name='Car about')),
                ('year', models.IntegerField(verbose_name='Car year')),
            ],
        ),
        migrations.CreateModel(
            name='sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images', verbose_name='Car image')),
                ('image2', models.ImageField(upload_to='images', verbose_name='Car image')),
                ('image3', models.ImageField(upload_to='images', verbose_name='Car image')),
                ('image4', models.ImageField(upload_to='images', verbose_name='Car image')),
                ('image5', models.ImageField(upload_to='images', verbose_name='Car image')),
                ('image6', models.ImageField(upload_to='images', verbose_name='Car image')),
            ],
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
