# Generated by Django 5.0.7 on 2024-09-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_car2_sign_delete_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='image1',
            field=models.ImageField(upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='image2',
            field=models.ImageField(upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='image3',
            field=models.ImageField(upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='image4',
            field=models.ImageField(upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='image5',
            field=models.ImageField(upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='image6',
            field=models.ImageField(upload_to='brands/'),
        ),
    ]
